# Generated by Django 6.0.2 on 2026-04-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dev_toolkit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código'),
        ),
    ]
