# Generated by Django 6.0.7 on 2026-07-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dev_toolkit', '0002_language_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='is_ui',
            field=models.BooleanField(default=True, help_text='Visible in language switcher', verbose_name='UI'),
        ),
    ]
