# Generated by Django 6.0.2 on 2026-04-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Nombre')),
                ('is_rtl', models.BooleanField(default=False, verbose_name='RTL')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'ordering': ['name'],
            },
        ),
    ]
