# Generated by Django 6.0.5 on 2026-05-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/originals/')),
                ('photo_webp', models.ImageField(blank=True, editable=False, null=True, upload_to='products/webp/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
